[book]
authors = ["redblue0216"]
language = "en"
multilingual = false
src = "src"
title = "概率统计100问"


[preprocessor.katex]
after = ["links"]


[output.html]
git-repository-url = "https://github.com/redblue0216/Book_ProbablityStatistics100Tips"
